### ISSUE TITLE
[New.nsec + Nostrkeys] Incorrect username sent on nostr.json?name= request

### ISSUE THREAD

**Issue by leafes** [nostrband/nostr-login#127]
**Steps:** 
1. Sign up through widget on nostrkeys
2. Select "With keystore" option 
3. Select new.nsec.app
4. Set user name (ex. testuser001) 

repeat this process 2 times, set different name second time (e.g. testuser002)

**Actual result:** 
After form submittion request with default generated user name (e.g. bright-fish-97) as name parameter is sent.
Nostr.json returns 502. 

`error: Failed to fetch nip05 bright-fish-97@new.nsec.app error: TypeError: Failed to fetch`

screencast: 

https://jam.dev/c/3278541e-de71-4671-bde1-c145bb51ff77

**Expected:** 
nostr.json?name=testuser001 is sent. 200 OK response. Open pop-up with new.nsec.app to set password for testuser001

Was able to replicate **only on new** version of widget.

**Comment by nostrband** [comment]
The default generated username is checked by the nsec.app iframe that's being injected to present the Continue button. It was returning 502 because of the related bug https://github.com/nostrband/nostr-login/issues/128 
Ideally we should suppress log printing by nsec.app iframe and also make it only execute necessary operations, but for now that's not harming anyone - server should be fixed now.

**Comment by leafes** [comment]
server 502 issue is fixed within https://github.com/nostrband/nostr-login/issues/128
